import { Inter, Open_Sans } from "next/font/google";
import "./globals.css";
import BazaHeader from "./TheHeader/BazaHeader";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const open_sans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ua" className={`${open_sans.variable} ${inter.variable}`}>
      <body>
        <BazaHeader />
        <main className="main">{children}</main>
      </body>
    </html>
  );
}
